import React, { useEffect, useState } from 'react';
import { Check, Loader2, RefreshCw, X } from 'lucide-react';
import { auth } from '../../firebase';

export const AdminTopupReviewView: React.FC = () => {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const token = await auth.currentUser?.getIdToken(); const r = await fetch('/api/admin/topup-submissions', { headers: { Authorization: `Bearer ${token}` } }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setItems(d.submissions || []); } catch (e:any) { setError(e.message || 'โหลดรายการไม่สำเร็จ'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const review = async (submissionId: string, decision: 'APPROVE'|'REJECT') => { if (!confirm(decision === 'APPROVE' ? 'ยืนยันว่าเงินเข้าบัญชีธนาคารแล้ว และเพิ่มยอดเข้ากระเป๋า?' : 'ปฏิเสธรายการนี้?')) return; const token = await auth.currentUser?.getIdToken(); const r = await fetch('/api/admin/topup-review', { method:'POST', headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}, body:JSON.stringify({submissionId,decision}) }); const d=await r.json(); if(!r.ok) setError(d.error || 'ดำเนินการไม่สำเร็จ'); else load(); };
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-white">ตรวจสลิปเติมเงิน</h2><p className="text-xs text-amber-200">ตรวจเงินเข้าบัญชีธนาคารจริงก่อนกดอนุมัติทุกครั้ง</p></div><button onClick={load} className="rounded-xl border border-cyan-400/40 p-2 text-cyan-300"><RefreshCw className="w-4 h-4"/></button></div>{error&&<p className="rounded-xl bg-red-500/10 p-3 text-red-300">{error}</p>}{loading?<Loader2 className="mx-auto animate-spin"/>:items.length===0?<p className="rounded-2xl bg-white/5 p-6 text-center text-slate-400">ไม่มีสลิปรอตรวจ</p>:items.map(item=><div key={item.id} className="rounded-2xl border border-white/10 bg-[#0A1633] p-4"><div className="grid gap-2 text-sm sm:grid-cols-2"><p>ผู้ใช้: {item.userEmail || item.userId}</p><p className="font-black text-emerald-300">฿{(item.amountSatang/100).toLocaleString()}</p><p>เลขอ้างอิง: {item.reference}</p><p>ผู้รับที่ AI อ่าน: {item.extracted?.recipientName}</p></div><div className="mt-4 flex gap-2"><button onClick={()=>review(item.id,'APPROVE')} className="flex-1 rounded-xl bg-emerald-400 p-2 font-black text-slate-950"><Check className="mr-1 inline w-4 h-4"/>เงินเข้าแล้ว อนุมัติ</button><button onClick={()=>review(item.id,'REJECT')} className="rounded-xl bg-red-500/20 px-4 text-red-300"><X className="w-4 h-4"/></button></div></div>)}</div>;
};
