import React, { useEffect, useState } from 'react';
import { WIN_IMAGES } from '../../data/imageRegistry';
import { Check, ImageOff, Loader2, RefreshCw, X } from 'lucide-react';
import { auth } from '../../firebase';

async function readJsonSafely(response: Response): Promise<any> { const text = await response.text(); if (!text.trim()) return {}; try { return JSON.parse(text); } catch { throw new Error(response.ok ? 'เซิร์ฟเวอร์ส่งข้อมูลที่ไม่ใช่ JSON' : `เซิร์ฟเวอร์ไม่พร้อม (${response.status})`); } }

const SlipImage: React.FC<{ submissionId: string; hasProof: boolean }> = ({ submissionId, hasProof }) => {
  const [src, setSrc] = useState(''); const [failed, setFailed] = useState(!hasProof);
  useEffect(() => { if (!hasProof) return; let objectUrl = ''; let cancelled = false;
    void auth.currentUser?.getIdToken().then(async (token) => { if (!token) throw new Error('เซสชันแอดมินหมดอายุ'); const response = await fetch(`/api/admin/topup-proof/${encodeURIComponent(submissionId)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'image/*,application/json' } }); if (!response.ok) throw new Error('โหลดภาพไม่สำเร็จ'); const blob = await response.blob(); if (blob.size === 0) throw new Error('ไฟล์ภาพสลิปว่าง'); objectUrl = URL.createObjectURL(blob); if (!cancelled) setSrc(objectUrl); }).catch(() => { if (!cancelled) setFailed(true); });
    return () => { cancelled = true; if (objectUrl) { try { URL.revokeObjectURL(objectUrl); } catch {} } };
  }, [submissionId, hasProof]);
  if (failed) return <div className="flex min-h-56 items-center justify-center rounded-2xl border border-dashed border-white/15 bg-black/30 text-xs text-slate-500"><ImageOff className="mr-2 h-5 w-5" />รายการเดิมไม่มีภาพสลิปที่จัดเก็บไว้</div>;
  if (!src) return <div className="flex min-h-56 items-center justify-center rounded-2xl bg-black/30"><Loader2 className="h-6 w-6 animate-spin text-cyan-300" /></div>;
  return <a href={src} target="_blank" rel="noreferrer" title="เปิดภาพสลิปขนาดเต็ม"><img src={src} alt="ภาพสลิปที่ผู้ใช้อัปโหลด" className="max-h-[520px] w-full rounded-2xl border border-white/10 bg-black/30 object-contain" /></a>;
};

export const AdminTopupReviewView: React.FC = () => {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error('กรุณาเข้าสู่ระบบ Super Admin ใหม่'); const response = await fetch('/api/admin/topup-submissions', { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } }); const data = await readJsonSafely(response); if (!response.ok) throw new Error(data.error || 'โหลดรายการไม่สำเร็จ'); setItems(data.submissions || []); } catch (e: any) { const msg = String(e?.message || 'โหลดรายการไม่สำเร็จ'); setError(msg === 'The string did not match the expected pattern.' ? 'เซิร์ฟเวอร์ส่งข้อมูลไม่ถูกต้อง — ระบบตรวจ JSON ก่อนอ่านแล้ว กรุณาตรวจเซิร์ฟเวอร์อีกครั้ง' : msg); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const review = async (submissionId: string, decision: 'APPROVE' | 'REJECT') => { if (!confirm(decision === 'APPROVE' ? 'ยืนยันว่าเทียบภาพสลิปและตรวจเงินเข้าบัญชีธนาคารแล้ว?' : 'ปฏิเสธรายการนี้?')) return; try { const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error('เซสชันแอดมินหมดอายุ'); const response = await fetch('/api/admin/topup-review', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ submissionId, decision }) }); const data = await readJsonSafely(response); if (!response.ok) throw new Error(data.error || 'ดำเนินการไม่สำเร็จ'); await load(); } catch (e: any) { setError(String(e?.message || 'ดำเนินการไม่สำเร็จ')); } };
  return <div className="space-y-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><img src={WIN_IMAGES.admin.topupReview} alt="ตรวจสลิปเติมเงิน" className="w-10 h-10 rounded-2xl object-cover ring-1 ring-emerald-400/50 shadow-sm" /><div><h2 className="text-xl font-black text-white">ตรวจสลิปเติมเงิน</h2><p className="text-xs text-amber-200">เทียบภาพสลิปกับข้อมูล AI และตรวจเงินเข้าบัญชีธนาคารก่อนอนุมัติ</p></div></div><button onClick={() => void load()} disabled={loading} className="rounded-xl border border-cyan-400/40 p-2 text-cyan-300 disabled:opacity-50"><RefreshCw className="h-4 w-4" /></button></div>{error && <p className="rounded-xl bg-red-500/10 p-3 text-red-300">{error}</p>}{loading ? <Loader2 className="mx-auto animate-spin" /> : items.length === 0 ? <p className="rounded-2xl bg-white/5 p-6 text-center text-slate-400">ไม่มีสลิปรอตรวจ</p> : items.map((item) => <article key={item.id} className="grid gap-4 rounded-2xl border border-white/10 bg-[#0A1633] p-4 lg:grid-cols-[minmax(260px,0.8fr)_1fr]"><SlipImage submissionId={item.id} hasProof={Boolean(item.proofStoragePath)} /><div className="space-y-4"><div className="grid gap-2 text-sm sm:grid-cols-2"><p>ผู้ใช้: {item.userEmail || item.userId}</p><p className="font-black text-emerald-300">ยอดที่แจ้ง ฿{(item.amountSatang / 100).toLocaleString()}</p><p>ยอดที่ AI อ่าน: ฿{Number(item.extracted?.amount || 0).toLocaleString()}</p><p>ความมั่นใจ AI: {Math.round(Number(item.extracted?.confidence || 0) * 100)}%</p><p className="break-all">เลขอ้างอิง: {item.reference}</p><p>ผู้รับที่ AI อ่าน: {item.extracted?.recipientName}</p><p>บัญชีปลายทาง: {item.extracted?.recipientAccountHint || 'ไม่พบ'}</p><p>วันเวลาโอน: {item.extracted?.transferDateTime || 'ไม่พบ'}</p></div><p className="rounded-xl border border-amber-400/20 bg-amber-500/10 p-3 text-xs text-amber-100">ภาพและ AI ไม่ยืนยันว่าเงินเข้าจริง ต้องตรวจรายการเดินบัญชีธนาคารก่อนกดอนุมัติ</p><div className="flex gap-2"><button onClick={() => void review(item.id, 'APPROVE')} disabled={!item.proofStoragePath} className="flex-1 rounded-xl bg-emerald-400 p-2 font-black text-slate-950 disabled:opacity-40"><Check className="mr-1 inline h-4 w-4" />เงินเข้าแล้ว อนุมัติ</button><button onClick={() => void review(item.id, 'REJECT')} className="rounded-xl bg-red-500/20 px-4 text-red-300"><X className="h-4 w-4" /></button></div></div></article>)}</div>;
};
